[package]
name = "bonecoin-core"
description = "Core types, methods, and interfaces to work with the bonecoin blockchain."
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
